# Generated by Django 5.2.13 on 2026-06-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
    ]
