# Generated by Django 6.0.6 on 2026-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='students_attended',
            field=models.ManyToManyField(blank=True, to='users.student'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('schedule', 'session_date'), name='unique_session_per_schedule_date'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('special_schedule__isnull', False)), fields=('special_schedule', 'session_date'), name='unique_session_per_special_date'),
        ),
    ]
